import { describe, it, expect } from 'vitest'
import { buildPerfGames } from '../lib/perfEngine/perfGamesList'
import perfGames from '../data/perfGames.json'
import legacyGames from '../data/gamesData.json'
import meta from '../../data/games/gameMeta.json'
import entries from '../../data/benchmarks/entries.json'

// The gate. perfGames.json is generated by `npm run perf:games`, and this fails
// when the committed file no longer matches what the corpus would produce —
// which is what happens when somebody imports measurements and forgets to
// regenerate, exactly as sitemap.test.js guards `npm run sitemap`.
describe('perfGames.json is derived from the corpus', () => {
  const built = buildPerfGames({ meta, entries, legacy: legacyGames })

  it('builds without problems against the real corpus', () => {
    expect(built.problems).toEqual([])
  })

  it('matches the committed file exactly — run `npm run perf:games` if this fails', () => {
    expect(perfGames).toEqual(built.games)
  })

  it('lists no game the corpus does not measure', () => {
    const measured = new Set(entries.filter((e) => !e.supersededBy).map((e) => e.gameId))
    const listed = perfGames.map((g) => g.id)
    expect(listed.filter((id) => !measured.has(id))).toEqual([])
  })

  it('lists every game the corpus does measure', () => {
    const measured = [...new Set(entries.filter((e) => !e.supersededBy).map((e) => e.gameId))]
    const listed = new Set(perfGames.map((g) => g.id))
    expect(measured.filter((id) => !listed.has(id))).toEqual([])
  })

  it('lists no preset the corpus does not hold for that game', () => {
    const held = new Map()
    for (const e of entries.filter((x) => !x.supersededBy)) {
      if (!held.has(e.gameId)) held.set(e.gameId, new Set())
      held.get(e.gameId).add(e.presetId)
    }
    const stray = []
    for (const g of perfGames) {
      for (const p of g.presets) if (!held.get(g.id)?.has(p.id)) stray.push(`${g.id}|${p.id}`)
    }
    expect(stray).toEqual([])
  })

  it('has unique ids', () => {
    expect(new Set(perfGames.map((g) => g.id)).size).toBe(perfGames.length)
  })

  it('never contradicts the legacy list about a shared id', () => {
    // cs2, cyberpunk, bg3 and friends exist in both. Two different display names
    // for one id would show a reader two different games depending on which
    // screen they are on.
    const legacyById = new Map(legacyGames.map((g) => [g.id, g]))
    const clashes = perfGames
      .filter((g) => legacyById.has(g.id) && legacyById.get(g.id).name !== g.name)
      .map((g) => `${g.id}: "${g.name}" vs "${legacyById.get(g.id).name}"`)
    expect(clashes).toEqual([])
  })
})
