import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { PAGES } from '../hooks/usePageRoute'
import { pagedParts, partPath, hasPartPage } from '../lib/partPages'
import parts from '../data/partsData.json'

const SITE = 'https://custompcbuilder.netlify.app'
// resolve off cwd, not import.meta.url: under jsdom that is an http:// URL and
// readFileSync rejects it. Same approach as cspHeaders.test.js.
const xml = readFileSync(resolve(process.cwd(), 'public/sitemap.xml'), 'utf8')
const locs = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1])

// The sitemap is generated (scripts/build-sitemap.mjs) because it is now 551
// URLs, and a catalogue widening changes the set. This is the guard that a
// widening was actually followed by `npm run sitemap`: a stale sitemap is worse
// than none, since it offers a crawler URLs that 404 and withholds real ones.
describe('the shipped sitemap matches what the site actually serves', () => {
  it('is well formed and free of duplicates', () => {
    expect(xml.startsWith('<?xml version="1.0" encoding="UTF-8"?>')).toBe(true)
    expect(xml).toContain('</urlset>')
    expect(new Set(locs).size).toBe(locs.length)
  })

  // The trailing slash is the point, not an accident: each content page ships as
  // dist/<page>/index.html, so the slashed URL is the 200 and the bare one is a
  // 301. A sitemap is meant to list canonical URLs.
  it('lists the root and every content page, in its canonical slashed form', () => {
    expect(locs).toContain(`${SITE}/`)
    for (const page of PAGES) {
      expect(locs, page).toContain(`${SITE}/${page}/`)
      expect(locs, `${page} must not be listed unslashed — that URL 301s`).not.toContain(`${SITE}/${page}`)
    }
  })

  it('lists every part that has a page', () => {
    const listed = new Set(locs)
    for (const part of pagedParts(parts)) {
      expect(listed.has(`${SITE}${partPath(part)}`), `${part.id} missing from sitemap`).toBe(true)
    }
  })

  // The other direction, which is the one that rots: a part removed from the
  // catalogue leaves a URL behind that now 404s.
  it('lists nothing that is not served', () => {
    const known = new Set([`${SITE}/`, ...PAGES.map((p) => `${SITE}/${p}/`)])
    for (const loc of locs) {
      if (known.has(loc)) continue
      const id = loc.slice(`${SITE}/parts/`.length)
      expect(loc.startsWith(`${SITE}/parts/`), loc).toBe(true)
      const part = parts.find((p) => p.id === id)
      expect(part, `${loc} is in the sitemap but not the catalogue`).toBeTruthy()
      expect(hasPartPage(part), `${loc} has no page`).toBe(true)
    }
  })

  it('holds exactly the root, the content pages and the paged parts', () => {
    expect(locs.length).toBe(1 + PAGES.length + pagedParts(parts).length)
  })

  it('says it is generated, so nobody hand-edits it', () => {
    expect(xml).toMatch(/GENERATED by scripts\/build-sitemap\.mjs/)
  })
})
