// Regenerates public/sitemap.xml from the router and the catalogue.
//
//   npm run sitemap
//
// It has to be generated. The content pages were a hand-written list of seven,
// which was maintainable; a URL per catalogue part is 540 more, and every
// catalogue widening changes the set. A stale sitemap is worse than none — it
// offers a crawler URLs that 404 and withholds the ones that exist.
//
// The module list is loaded through Vite rather than by plain `node` on purpose:
// the app's modules use extensionless relative imports, which Node's ESM resolver
// rejects, and re-listing the pages or the paged categories here would be a
// second definition of both — exactly the drift this script exists to prevent.
// Vite is already a dependency, so this costs nothing extra.
import { writeFileSync, readFileSync } from 'node:fs'
import { pathToFileURL } from 'node:url'
import { createServer } from 'vite'

const SITE = 'https://custompcbuilder.netlify.app'
const OUT = new URL('../public/sitemap.xml', import.meta.url)

// Content pages keep the priorities they were given by hand; part pages sit
// below them. A part page is real content, but the root and the browser are the
// way in.
const PAGE_PRIORITY = {
  '': { priority: '1.0', changefreq: 'weekly' },
  parts: { priority: '0.9', changefreq: 'weekly' },
  help: { priority: '0.8', changefreq: 'monthly' },
  glossary: { priority: '0.8', changefreq: 'monthly' },
  feedback: { priority: '0.4', changefreq: 'monthly' },
  privacy: { priority: '0.3', changefreq: 'yearly' },
  terms: { priority: '0.3', changefreq: 'yearly' },
}

const PART_ENTRY = { priority: '0.6', changefreq: 'monthly' }

const entry = ({ loc, changefreq, priority }) => `  <url>
    <loc>${loc}</loc>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`

export async function buildSitemap() {
  const server = await createServer({
    server: { middlewareMode: true },
    logLevel: 'error',
    // Nothing is served; this is only here to resolve and evaluate modules.
    appType: 'custom',
  })
  try {
    const { PAGES } = await server.ssrLoadModule('/src/hooks/usePageRoute.js')
    const { pagedParts, partPath } = await server.ssrLoadModule('/src/lib/partPages.js')
    const { default: parts } = await server.ssrLoadModule('/src/data/partsData.json')

    // Content pages carry a TRAILING SLASH because the pre-render writes each one
    // as dist/<page>/index.html (apply-prerender.mjs). The slashed form is the
    // directory index and serves 200; the bare form gets Netlify's directory
    // redirect, so listing it would point a crawler at a 301. Part pages are NOT
    // pre-rendered as directories — they resolve through the SPA fallback either
    // way — so partPath() is left alone.
    const urls = [
      { loc: `${SITE}/`, ...PAGE_PRIORITY[''] },
      ...PAGES.map((p) => ({ loc: `${SITE}/${p}/`, ...(PAGE_PRIORITY[p] ?? PART_ENTRY) })),
      // Sorted by id so the file's diff shows what actually changed when the
      // catalogue grows, rather than reordering wholesale.
      ...pagedParts(parts)
        .slice()
        .sort((a, b) => a.id.localeCompare(b.id))
        .map((part) => ({ loc: `${SITE}${partPath(part)}`, ...PART_ENTRY })),
    ]

    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by scripts/build-sitemap.mjs — do not edit by hand.
     Run \`npm run sitemap\` after any catalogue change or new content page.
     sitemap.test.js fails if this file and the catalogue disagree. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(entry).join('\n')}
</urlset>
`
    return { xml, count: urls.length }
  } finally {
    await server.close()
  }
}

// Only writes when run directly, so the test can import and compare instead.
// pathToFileURL rather than string-building the URL: on Windows argv[1] is a
// backslash path with a drive letter, and a hand-built `file://` + path silently
// never matches (it needs three slashes), so the script would exit doing nothing.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { xml, count } = await buildSitemap()
  const before = (() => { try { return readFileSync(OUT, 'utf8') } catch { return '' } })()
  writeFileSync(OUT, xml)
  console.log(`sitemap.xml: ${count} URLs${before === xml ? ' (unchanged)' : ' (updated)'}`)
}
